/*******************************************************************

  THIS FILE IS GENERATED BY RUNNING simple1.json and simple2.json
  WITH ./jsondiff

*******************************************************************/



/* file: jsondiffcmds.c
 * Generated functions to migrate schema.
 * TODO: (somehow enable the user to) fill in the initialization
 *       values for (your_new_default_val).
 */

#include <jansson.h>
#include <string.h>
/* All user-defined variables must be strings (put int's in "'s).*/
#define DEFAULT_delta "9" 


/* Declarations */
void upd_menu(json_t * parent);
void upd_popup(json_t * parent);


/* The update funcion: */
void update_json(json_t * parent, const char* key){
  if(strncmp(key, "menu", 4) == 0){
    upd_menu(parent);
    return;
  }
  if(strncmp(key, "popup", 5) == 0){
    upd_popup(parent);
    return;
  }
  printf("ERROR!!! Did not find match TODO");
}



/* Migration functions */
void upd_menu(json_t * parent){
  json_t * obj = json_object_get(parent, "menu");

  json_object_del(obj, "deleteme");
  json_object_set(obj, "delta", json_string(DEFAULT_delta));
  upd_popup(obj);

}
void upd_popup(json_t * parent){
  json_t * obj = json_object_get(parent, "popup");

}

